# ビルドステージ
FROM ruby:3.2 AS builder
RUN apt-get update -qq
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install
COPY . /app

# プロダクションステージ
FROM ruby:3.2
COPY --from=builder /app /app
WORKDIR /app
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "production"]