# 
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.5'

gem 'bootsnap', '>= 1.4.4', require: false

gem 'dotenv'

# データベース(postgresql)
gem 'pg', '>= 0.18', '< 2.0'

# Puma
gem 'puma', '~> 5.0'

# SassのRailsアダプター
# gem 'sass-rails', '>= 6'

# Webpacker
# gem 'webpacker', '~> 5.0'

# Turbolinks
gem 'turbolinks', '~> 5'

# Jbuilder
gem 'jbuilder', '~> 2.7'

# Redis
gem 'redis', '~> 4.0'

# Active Model Serializers
gem 'active_model_serializers', '~> 0.10.0'

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# デバッグツール
group :development, :test do
  # コールスタックの改善
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # テスト
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 4.0'
  # ホットリロードさせる
  gem 'hotwire-livereload'
end

group :development do
  # アクセス解析
  # N+1問題を検出するためのgem
  # gem 'bullet', '~> 6.1'
  gem 'rack-mini-profiler', '~> 2.0'
  # コードの品質保証
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  # Windows ではCygwinを介してコマンドラインツールを使用
  gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
end
