name: 'Validate PR title'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # dependabotでは `secrets.GITHUB_TOKEN` を参照できないためスキップ
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/amannn/action-semantic-pull-request#configuration
        with:
          # タイトルのprefixに [WIP] があれば検証を保留にする
          wip: true
          # これらのラベルが付いているものは検証の対象外にする
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          # 許可するスコープ。スコープとは、コミットの型の後ろに書いてある丸括弧の中身のこと
          # e.g. "chore(deps)" の "deps" の部分
          scopes: |
            deps
            deps-dev
